/* Problem Set 3 - 16, 17, 18 Chapter 3 Object-Oriented Data Structures Using Java, 4th Edition
-------------------------------------------------------------*
/*
Name: Patricia Antlitz
Date: 10/05/2022
Class: CIS-252 Computer Science II - NECC Fall 2022

 * Please read the README file for detailed information about this program.

 * This file is the main class that runs this program
 * newList object is created from the LinkedList.java which uses a node list from LLNode.java
 * The following file is NOT original to this code (not coded by me - belongs to the book):
    * LLNode.java
 * This program will generate a nodeList of 10 random numbers from 1-20, created by generateNums() from LinkedList.java.
 * It will insert the numbers generated into a nodeList called listLink.
 * It will check which numbers are even and print them.
 * to confirm, it also prints the total number of even numbers (how many are there)
 * Another random number from 1-20 is generated in the main file. This number will be passed as a parameter for the
 methods contains() and remove(). contains() will check if this number is present in the list. it will print the number,
 and if it was found, or not. remove() will check if that same number is there, and remove it if it is. It then prints the
 final list.
 * These numbers are all randomly generated by the program. Running the program several times might be necessary to test all
 the methods.
*/

/**
 * @author Patricia N. Antlitz
 * @version 1.0
 */

public class ProblemSet_3_PatriciaAntlitz
{
    public static void main(String[] args)
    {
        LinkedList newList = new LinkedList();
        //random number to pass a parameter for contains() and remove()
        int random = (int) (Math.random() * (20 - 1)) + 1;

        System.out.println("Numbers on This List:");
        newList.generateNums();

        System.out.print("\n\nEven Numbers are: ");
        newList.numEvens(newList.listLink);
        System.out.println("\nTotal Even Numbers: " + newList.printEvens(newList.listLink));

        System.out.println();
        System.out.println("Target = " + random);

        //contains()
        //if the random number exist
        if(newList.contains(random, newList.listLink)){
            //then the target was found
            System.out.println("Target Found!");
            newList.contains(random, newList.listLink);
        }
        else{
            //if not
            System.out.println("Target Not Found!");
        }

        System.out.println("\nFinal List: ");
        newList.remove(random, newList.listLink);
    }
}
